[package]
name = "cargo-license"
description = "Cargo subcommand to see license of dependencies"
authors = ["Onur Aslan <onur@onur.im>"]
version = "0.4.1"
license = "MIT"
readme = "README.md"
repository = "https://github.com/onur/cargo-license"
edition = "2018"

[dependencies]
getopts = "0.2.21"
toml = "0.5.8"
ansi_term = "0.12.1"
csv = "1.1.6"
serde = "1.0.127"
serde_derive = "1.0.127"
serde_json = "1.0.66"
cargo_metadata = "0.14.0"
semver = "1.0.4"
structopt = "0.3.22"
atty = "0.2.14"
anyhow = "1.0.42"
